config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :tags
  resources :videos
  resources :channels
  resources :users
  get 'login' , to: 'users#login'
  post 'login' , to: 'users#check_login'
  get 'main' , to: 'users#main'
  get 'test' , to: 'users#test'
  get 'my_channel' , to:'channels#my_channel'
  post 'my_channel' , to:'channels#my_channel'
  delete 'Log-out' , to: 'users#logout'
  post 'channels/new' , to: 'channels#new'
  get 'tag/:tag' , to: 'videos#select_tag'
  get '/all_channel' , to: 'channels#all_channel'
  get 'channel/:channel_name' , to: 'channels#this_channel'
  get 'select_tag' , to: 'videos#select_tag'
  get 'tag' , to: 'videos#show_tag'
  post '/channels/:id/follow', to: "channels#follow", as: "follow_channel"
  post '/channels/:id/unfollow', to: "channels#unfollow", as: "unfollow_channel"
  post '/videos/:id/like', to: "videos#like", as: "like_channel"
  post '/videos/:id/unlike', to: "videos#unlike", as: "unlike_channel"
  post '/videos/:id' , to: 'videos#create_comment'
  post '/follow/:tag', to: "videos#follow_tag"
  post '/unfollow/:tag', to: "videos#unfollow_tag"
  post 'select_tag' , to: 'videos#select_tag'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :user
  has_many :videos
  has_one_attached :thumbnail
  has_many :follows
  has_many :users, through: :follows
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: %i[ show edit update destroy ]

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
  end
  # GET /channels/1 or /channels/1.json
  def show
    @current_user = User.find_by(id:session[:user_id])
    @channel_followed= @current_user.channels
    @channel = Channel.find_by(id:params[:id])
    @allvideo = @channel.videos
    puts @channel.user_id
    puts @current_user.id
  end
  def my_channel
    @current_user = User.find_by(id:session[:user_id])
    @channel_followed= @current_user.channels
    @channel = Channel.find_by(user_id:session[:user_id])
    @allvideo = @channel.videos
  end
  def all_channel
    @channels = Channel.all
    @current_user = User.find_by(id:session[:user_id])
    @channel_followed= @current_user.channels
  end
  def this_channel
    @current_user = User.find_by(id:session[:user_id])
    @channel_followed= @current_user.channels
    @channel= Channel.find_by(channel_name:params[:channel.channel_name])
  end
  def follow
    @channel = Channel.find_by(id:params[:id])
    @current_user = User.find_by(id:session[:user_id])
    @new_follow = Follow.new(user_id:@current_user.id,channel_id:@channel.id)
    @new_follow.save
    redirect_to channel_path(@channel.id)
  end
  def unfollow
    @channel = Channel.find_by(id:params[:id])
    @current_user = User.find_by(id:session[:user_id])
    @destroy = Follow.find_by(user_id:@current_user.id,channel_id:@channel.id)
    @destroy.destroy
    redirect_to channel_path(@channel.id)
  end

  # GET /channels/new
  def new
    @current_user = User.find_by(id:session[:user_id])
    @channel_followed= @current_user.channels
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end
  # POST /channels or /channels.json
  def create
    @channel = Channel.new(channel_params)
    @channel.user_id = session[:user_id]
    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1 or /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to my_channel_path, notice: "Channel was successfully updated." }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:channel_name, :about, :user_id , :thumbnail)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :channel_name %>
    <%= form.text_area :channel_name %>
  </div>
   <div class="field">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
  </div> 
  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/all_channel.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
#head {
  color:purple;
  font-size: 22px;
  background-color: white;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
    <% @channel_followed.each do |channel| %>
          <a href="channels/<%= channel.id %>" ><%= channel.channel_name %></a>  
    <% end %>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <h1> ALL CHANNEL </h1>
  <table margin="5px">
    <tr>
      <% @channels.each do |channel| %>
      <td>
        <div class="card" style="width: 18rem;">
          <% if channel.thumbnail.attached? %>
          <%= image_tag(channel.thumbnail , style:'width:100%; height:auto') %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title">Channel: <%= channel.channel_name %></h5>
            <p class="card-text"><%= channel.about %></p>
            <a href="channels/<%= channel.id %>" class="btn btn-primary" id="see_channel">See channel!!</a>
          </div>
        </div>
      </td>
      <% end %>
      </tr>
    </table>
  </div>
</body>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table>
  <thead>
    <tr>
      <th>Channel name</th>
      <th>About</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.channel_name %></td>
        <td><%= channel.about %></td>
        <td><%= channel.user_id %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/my_channel.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
#head {
  color:purple;
  font-size: 22px;
  background-color: white;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
    <% @channel_followed.each do |channel| %>
          <a href="channels/<%= channel.id %>" ><%= channel.channel_name %></a>  
    <% end %>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <div>
      <%= button_to "Upload Video" ,"/videos/new" ,class:"btn btn-primary mt-2 " ,style: "background-color: #6441a5; color:white;" ,method:"get" %>
  </div>
  <div class="card" style="width: 500px;">
      <%= image_tag(@channel.thumbnail , style:'width:auto; height:auto') %>
      <div class="card-body">
        <h5 class="card-title">Channel: <%= @channel.channel_name %></h5>
        <p class="card-text"><%= @channel.about %></p>
     </div>
    </div>
  <table margin="5px">
    <tr>
      <% @allvideo.each do |video| %>
      <td>
        <div class="card" style="width: 18rem;">
          <%= image_tag(video.thumbnail , style:'width:100%; height:auto') %>
          <div class="card-body">
            <h5 class="card-title">Tittle: <%= video.title %></h5>
            <p class="card-text"><%= video.description %></p>
            <a href="http://127.0.0.1:3000/videos/<%= video.id %>" class="btn btn-primary">Watch Now!!</a>
            <a href="tag/<%= video.tag %>" class="btn btn-primary" style="background-color:#6441a5;"> Tag: <%= video.tag %> </a>
          </div>
        </div>
      </td>
      <% end %>
      </tr>
    </table>
  </div>
</body>

app/views/channels/new.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
    <% @channel_followed.each do |channel| %>
          <a href="channels/<%= channel.id %>" ><%= channel.channel_name %></a>  
    <% end %>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="/tag">Tag</a>
          <a class="navbar-brand" href="#">All Channel</a>
          <a class="navbar-brand" href="/channels/new">Your channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <div>
    <%= render 'form', channel: @channel %>
    <%= link_to 'Back', channels_path %>
  </div>
</body>

app/views/channels/show.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
#head {
  color:purple;
  font-size: 22px;
  background-color: white;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
     <% @channel_followed.each do |channel| %>
          <a href="channels/<%= channel.id %>" ><%= channel.channel_name %></a>  
    <% end %>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="/select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <h1>THIS CHANNEL</h1>
    <div class="card" style="width: 500px;">
      <% if @channel.thumbnail.attached? %>
      <%= image_tag(@channel.thumbnail , style:'width:auto; height:auto') %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title">Channel: <%= @channel.channel_name %></h5>
        <p class="card-text"><%= @channel.about %></p>
        <% if @current_user.channels.include?(@channel) %>
          <h5><%= button_to "Unfollow", unfollow_channel_path, method: "POST" ,id:"unfollow" %></h5>
          <h4>followed for testcase</h4>
        <% else %>
          <h5><%= button_to "Follow", follow_channel_path, method: "POST" ,id:"follow"%></h5>
        <% end%>
     </div>
    </div>
  <h1> My video </h1>
  <% if @allvideo.count ==0 %>
  <p>This Channel have no content </p>
  <% end %>
  <table margin="5px">
    <tr>
      <% @allvideo.each do |video| %>
      <td>
        <div class="card" style="width: 18rem;">
          <% if video.thumbnail.attached? %>
          <%= image_tag(video.thumbnail , style:'width:100%; height:auto') %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title">Tittle: <%= video.title %></h5>
            <p class="card-text"><%= video.description %></p>
            <a href="http://127.0.0.1:3000/videos/<%= video.id %>" class="btn btn-primary" id="watch_now">Watch Now!!</a>
            <a href="http://127.0.0.1:3000/tag/<%= video.tag %>" class="btn btn-primary" style="background-color:#6441a5;"> Tag: <%= video.tag %> </a>
          </div>
        </div>
      </td>
      <% end %>
      </tr>
    </table>
  </div>
</body>

app/views/channels/this_channel.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a href="#">About</a>
    <a href="#">Services</a>
    <a href="#">Clients</a>
    <a href="#">Contact</a>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <div>
      <%= button_to "Upload Video" ,"/videos/new" ,class:"btn btn-primary mt-2 " ,style: "background-color: #6441a5; color:white;" ,method:"get" %>
  </div>
  <table border="5px">
    <tr>
      <% @allvideo.each do |video| %>
      <td>
        <div class="card" style="width: 18rem;">
          <%= image_tag(video.thumbnail , style:'width:100%; height:auto') %>
          <div class="card-body">
            <h5 class="card-title">Tittle: <%= video.title %></h5>
            <p class="card-text"><%= video.description %></p>
            <a href="http://127.0.0.1:3000/videos/<%= video.id %>" class="btn btn-primary">Watch Now!!</a>
            <a href="tag/<%= video.tag %>" class="btn btn-primary" style="background-color:#6441a5;"> Tag: <%= video.tag %> </a>
          </div>
        </div>
      </td>
      <% end %>
      </tr>
    </table>
  </div>
</body>