config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :tags
  resources :videos
  resources :channels
  resources :users
  get 'login' , to: 'users#login'
  post 'login' , to: 'users#check_login'
  get 'main' , to: 'users#main'
  get 'test' , to: 'users#test'
  get 'my_channel' , to:'channels#my_channel'
  post 'my_channel' , to:'channels#my_channel'
  delete 'Log-out' , to: 'users#logout'
  post 'channels/new' , to: 'channels#new'
  get 'tag/:tag' , to: 'videos#select_tag'
  get '/all_channel' , to: 'channels#all_channel'
  get 'channel/:channel_name' , to: 'channels#this_channel'
  get 'select_tag' , to: 'videos#select_tag'
  get 'tag' , to: 'videos#show_tag'
  post '/channels/:id/follow', to: "channels#follow", as: "follow_channel"
  post '/channels/:id/unfollow', to: "channels#unfollow", as: "unfollow_channel"
  post '/videos/:id/like', to: "videos#like", as: "like_channel"
  post '/videos/:id/unlike', to: "videos#unlike", as: "unlike_channel"
  post '/videos/:id' , to: 'videos#create_comment'
  post '/follow/:tag', to: "videos#follow_tag"
  post '/unfollow/:tag', to: "videos#unfollow_tag"
  post 'select_tag' , to: 'videos#select_tag'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :channel
	has_one_attached :clip
	has_one_attached :thumbnail
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
    if session[:user_id]== nil
      redirect_to login_path
    end
    @current_user = User.find_by(id:session[:user_id])
    if @current_user != nil
    @channel_followed= @current_user.channels
    end
    @video = Video.find_by(id:params[:id])
    @channel = @video.channel
    @comments = Comment.where(video_id:@video.id)
  end

  # GET /videos/new
  def new
    @video = Video.new
  end
  def create_comment
    @video = Video.find_by(id:params[:id])
    @comment = Comment.new()
    @comment.user_id = User.find_by(id:session[:user_id]).id
    @comment.comment = params[:body]
    @comment.video_id = @video.id
    @comment.save
    redirect_to video_path(@video.id)

  end
  def like
    @video = Video.find_by(id:params[:id])
    @current_user = User.find_by(id:session[:user_id])
    @new_like = Like.new(user_id:@current_user.id,video_id:@video.id)
    @new_like.save
    redirect_to video_path(@video.id)
  end
  def unlike
    @video = Video.find_by(id:params[:id])
    @current_user = User.find_by(id:session[:user_id])
    @destroy = Like.find_by(user_id:@current_user.id,video_id:@video.id)
    @destroy.destroy
    redirect_to video_path(@video.id)
  end
  def unfollow_tag
    @current_user = User.find_by(id:session[:user_id])
    @destroy = Tag.find_by(tag_name:params[:tag],user_id:@current_user.id)
    @destroy.destroy
    redirect_to select_tag_path
  end
  def follow_tag
    @current_user = User.find_by(id:session[:user_id])
    @follow = Tag.new(tag_name:params[:tag],user_id:@current_user.id)
    @follow.save
    redirect_to select_tag_path

  end
  # GET /videos/1/edit
  def edit
  end
  def select_tag
    if session[:user_id]== nil
      redirect_to login_path
    end
    @current_user = User.find_by(id:session[:user_id])
    if @current_user != nil
    @channel_followed= @current_user.channels
    end
  end
  def show_tag
    if session[:user_id]== nil
      redirect_to login_path
    end
    @current_user = User.find_by(id:session[:user_id])
    if @current_user != nil
    @channel_followed= @current_user.channels
    end
    @allvideo = Video.where(:tag => params[:name_tag])
  end

  # POST /videos or /videos.json
  def create
    @current_user = User.find_by(id:session[:user_id])
    if @current_user != nil
    @channel_followed= @current_user.channels
    end
    @video = Video.new(video_params)
    @channel = Channel.find_by(user_id:session[:user_id])
    @video.channel_id = @channel.id
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :tag, :clip ,:thumbnail)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>
 <div class="field">
   <%= form.label :clip %>
   <%= form.file_field :clip %>
 </div>
  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
  </div> 
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.select :tag, ["FPS","MOBA","RPG","GameCard","Strategy"]%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/all_tag.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #FFFFFF;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
#head {
  color:purple;
  font-size: 22px;
  background-color: white;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
     <% @channel_followed.each do |channel| %>
            <a href="channels/<%= channel.id %>" ><%= channel.channel_name %></a>  
      <% end %>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
          <a class="navbar-brand" href="/channels/new">Your channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <table margin="5px">
    <tr>
      <% @allvideo.each do |video| %>
      <td>
        <div class="card" style="width: 18rem;">
          <%= image_tag(video.thumbnail , style:'width:100%; height:auto') %>
          <div class="card-body">
            <h5 class="card-title">Tittle: <%= video.title %></h5>
            <p class="card-text"><%= video.description %></p>
            <a href="#" class="btn btn-primary">Watch Now!!</a>
            <a href="#" class="btn btn-primary" style="background-color:#6441a5;"> Tag: <%= video.tag %> </a>
          </div>
        </div>
      </td>
      <% end %>
      </tr>
    </table>
  </div>
</body>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= video.tag %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/select_tag.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
#head {
  color:purple;
  font-size: 22px;
  background-color: white;
}
.btn {
 background-color: #6441a5;
 color: white;
 margin: 5px;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
     <% @channel_followed.each do |channel| %>
            <a href="channels/<%= channel.id %>" ><%= channel.channel_name %></a>  
      <% end %>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <h1> ALL TAG </h1>
  <table margin="5px">
    <tr>
      <td>
        <div class="card" style="width: 18rem;">
          <img src="https://i.pinimg.com/474x/66/de/85/66de853a332d06413d3f6f39303ee366.jpg" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">FPS</h5>
            <a href="/tag/?name_tag=FPS" class="btn btn-primary" id="fortest_findvideo">Find Video</a>
            <% if Tag.find_by(user_id:@current_user.id,tag_name:'FPS')==nil %>
            <h5><%= button_to "Follow", "follow/FPS", method: "POST", class:"btn btn-primary" %></h5>
            <% else %>
            <h5><%= button_to "Unfollow", "unfollow/FPS", method: "POST", class:"btn btn-primary" %></h5>
            <% end %>
          </div>
      </td>
      <td>
        <div class="card" style="width: 18rem;">
          <img src="https://th.portal-pokemon.com/assets_c/2021/05/5dd2c1625486b50b90d76e4a53aeb3e8d3e179df-thumb-624xauto-16457.png" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">GAME CARD</h5>
            <a href="/tag/?name_tag=GameCard" class="btn btn-primary", id="g">Find Video</a>
            <% if Tag.find_by(user_id:@current_user.id,tag_name:'GameCard')==nil %>
            <h5><%= button_to "Follow", "follow/GameCard", method: "POST", class:"btn btn-primary" %></h5>
            <% else %>
            <h5><%= button_to "Unfollow", "unfollow/GameCard", method: "POST", class:"btn btn-primary" %></h5>
            <% end %>
        </div>
      </td>
      <td>
        <div class="card" style="width: 18rem;">
          <img src="https://www.mykhel.com/img/400x90/2020/04/dota-2-valve-1586941428.jpg" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">MOBA</h5>
            <a href="/tag/?name_tag=MOBA" class="btn btn-primary">Find Video</a>
            <% if Tag.find_by(user_id:@current_user.id,tag_name:'MOBA')==nil %>
            <h5><%= button_to "Follow", "follow/MOBA", method: "POST", class:"btn btn-primary" %></h5>
            <% else %>
            <h5><%= button_to "Unfollow", "unfollow/MOBA", method: "POST", class:"btn btn-primary" %></h5>
            <% end %>
            </div>
      </td>
      <td>
      <div class="card" style="width: 18rem;">
      <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/untitled-1-1-1566593533.jpg" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">RPG</h5>
        <a href="/tag/?name_tag=RPG" class="btn btn-primary">Find Video</a>
        <% if Tag.find_by(user_id:@current_user.id,tag_name:'RPG')==nil %>
            <h5><%= button_to "Follow", "follow/RPG", method: "POST", class:"btn btn-primary" %></h5>
            <% else %>
            <h5><%= button_to "Unfollow", "unfollow/RPG", method: "POST", class:"btn btn-primary" %></h5>
            <% end %>
      </div>
    </td>
    <td>
      <div class="card" style="width: 18rem;">
      <img src="https://media.wired.co.uk/photos/606dae60f19707fe1aef38f4/16:9/w_2560%2Cc_limit/CivilizationVI_screenshot_announce1.jpg" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">Strategy</h5>
        <a href="/tag/?name_tag=strategy" class="btn btn-primary">Find Video</a>
        <% if Tag.find_by(user_id:@current_user.id,tag_name:'Strategy')==nil %>
            <h5><%= button_to "Follow", "follow/Strategy", method: "POST", class:"btn btn-primary" %></h5>
            <% else %>
            <h5><%= button_to "Unfollow", "unfollow/Strategy", method: "POST", class:"btn btn-primary" %></h5>
            <% end %>
      </div>
    </div>
    </td>
      </tr>
    </table>
  </div>
</body>

app/views/videos/show.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
.card {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
        background-color: grey;
}
#head {
  color:purple;
  font-size: 22px;
  background-color: white;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="/select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  </div>
  <div>This video</div>
  <% if @channel.thumbnail.attached? %>
  <div class="card" style="width: 1000px;">
     <video id="my-video" class="video-js"controls preload="auto" width="1000" height="500" poster="<%= url_for(@video.thumbnail) %>" data-setup="{}">
        <source src="<%= url_for(@video.clip) %>" type="video/mp4" />
        <source src="MY_VIDEO.webm" type="video/webm" />
        <p class="vjs-no-js">
          <a href="https://videojs.com/html5-video-support/" target="_blank">
            supports HTML5 video
          </a>
        </p>
      </video>
    <div class="card-body">
      <link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />
        <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
      <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
      <p>
        <strong>Title:</strong>
        <%= @video.title %>
        <br>
        <strong>Description:</strong>
        <%= @video.description %>
        <% if @current_user.videos.include?(@video) %>
          <h5><%= button_to "Unlike", unlike_channel_path, method: "POST" %></h5>
        <% else %>
          <h5><%= button_to "Like", like_channel_path, method: "POST" %></h5>
        <% end%>
      </p>
    </div>
  </div>
  <div class="card" style="width: 500px;">
      <%= image_tag(@channel.thumbnail , style:'width:auto; height:auto') %>
      <div class="card-body">
        <h5 class="card-title">Channel: <%= @channel.channel_name %></h5>
        <p class="card-text"><%= @channel.about %></p>
     </div>
    </div>
    <% end %>
<div class="w3-container">
  <h4>Comment</h4>
    <% if @current_user %>
        <%= form_with model: @comment do |f| %>
            <%= f.text_field :body %>
            <%= f.submit  :comment %>

        <%end%>
    <%end%>
</div>
<div class="card">
    <% @comments.each do |comment| %>
        <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight"><%=comment.user_id%></div>
            <div class="p-2 flex-grow-1 bd-highlight"><%=comment.comment%></div>
            <div class="p-2 bd-highlight"><%=time_ago_in_words(comment.created_at)%></div> 
        </div>
        <hr>
    <%end%>
</div>
</body>

app/views/videos/show_tag.html.erb
<style>
html,body {
  font-family: "Lato", sans-serif;
  margin:0;
  padding: 0;
}

.sidenav {
  height: 100%;
  width: 200px;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #FFFFFF;
}
#main {
  padding: 0px;
  margin-left: 210px;
  width: 100wv;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  height: 40vh;
  flex-grow: 1;
}

img {
  max-height: 100%;
  min-width: 100%;
  object-fit: cover;
  vertical-align: bottom;
}
#head {
  color:purple;
  font-size: 22px;
  background-color: white;
}
.card{
  background-color:grey;
}
</style>
<% # frozen_string_literal: true %>
<body id="main"style="background-color: #848494;">
  <div id="mySidenav" class="sidenav">
    <a id="head">Followed Channel</a>
     <% @channel_followed.each do |channel| %>
            <a href="channels/<%= channel.id %>" ><%= channel.channel_name %></a>  
      <% end %>
  </div>
  <div class="row justify-content-start">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="/main">Home</a>
          <a class="navbar-brand" href="/select_tag">Tag</a>
          <a class="navbar-brand" href="/all_channel">All Channel</a>
        </div>
      </div>
      <div style="margin-right:30px">
        <%= button_to "Log-out" ,"/login" ,class:"btn btn-primary", style: "background-color: #6441a5;" %>
      </div>
    </nav>
  </div>
  <h1> Selectd Tag</h1>
  <table margin="5px">
    <tr>
       <% @allvideo.each do |video| %>
      <td>
        <div class="card" style="width: 18rem;">
          <%= image_tag(video.thumbnail , style:'width:100%; height:auto') %>
          <div class="card-body">
            <h5 class="card-title">Tittle: <%= video.title %></h5>
            <p class="card-text"><%= video.description %></p>
            <a href="http://127.0.0.1:3000/videos/<%= video.id %>" class="btn btn-primary">Watch Now!!</a>
            <a href="#" class="btn btn-primary" style="background-color:#6441a5;"> Tag: <%= video.tag %> </a>
          </div>
        </div>
      </td>
      <% end %>
      </tr>
    </table>
  </div>
</body>